#route contacte
admin_contact:
    path:     /contact
    defaults: { _controller: AdminBundle:Admin:Contact }

admin_contact_delete:
    path:     /contact/delet_{id}
    defaults: { _controller: AdminBundle:Admin:ContactDelete }
