#route membre
membre_liste:
    path:     /liste
    defaults: { _controller: AdminBundle:Membre:membre_list }

membre_profil:
    path:     /profil/{id}_{username}
    defaults: { _controller: AdminBundle:Membre:membre_profil }

membre_promote:
    path:     /profil/{id}_{username}/{role}
    defaults: { _controller: AdminBundle:Membre:promoteUser }
