membre_promot:
    path:     /promote/{user}/{role}
    defaults: { _controller: UserBundle:Membre:promoteUser}

membre_dispo:
    path:     /profil/dispo/add
    defaults: { _controller: UserBundle:Profile:dispo_add}

membre_animal:
    path:     /profil/animal/add
    defaults: { _controller: UserBundle:Profile:animal_add}

membre_message_lut:
    path:     /profil/message/{lut}
    defaults: { _controller: UserBundle:Profile:animal_add }
    options:
        expose: true