<?php

namespace UserBundle\Repository;

/**
 * AnimalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalsRepository extends \Doctrine\ORM\EntityRepository
{
}
