<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function isLut($statut, $user){
        $query = $this->createQueryBuilder('m')
            ->where('m.lut = :statut')
            ->andWhere('m.destinatair = :user')
            ->setParameter('statut', $statut)
            ->setParameter('user', $user);
        return $query->getQuery()->getResult();
    }
}
