<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function userVille(){
        $query = $this->createQueryBuilder('u');
        $query->select('u.adrVille');
        $query->groupBy('u.adrVille');

        return $query->getQuery()->getArrayResult();
    }

    public function by_roles($roles){
        $query = $this->createQueryBuilder('u');
        $query->where('u.roles LIKE :role');
        $query->setParameter('role', "%ROLE_".$roles."%");

        return $query->getQuery()->getArrayResult();
    }
}
