services:
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nala_user_registration }
    app.form.profil.edit:
        class: UserBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nala_user_profile }
#    user.example:
#        class: UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
