<?php

namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ContacteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContacteRepository extends EntityRepository
{
    public function New_Contacte(){
        $query = $this->createQueryBuilder('c')
            ->where('c.lut = 0')
            ->orderBy('c.date', 'ASC')
            ->setFirstResult(0)
            ->setMaxResults(5);
        return $query->getQuery()->getResult();
    }
}
